# Generated by Django 6.0.7 on 2026-07-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "license_category",
                    models.CharField(
                        choices=[
                            ("LMV", "Light Motor Vehicle"),
                            ("HMV", "Heavy Motor Vehicle"),
                            ("MCWG", "Motorcycle With Gear"),
                            ("OTHER", "Other"),
                        ],
                        default="LMV",
                        max_length=20,
                    ),
                ),
                ("license_expiry_date", models.DateField()),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "safety_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ON_TRIP", "On Trip"),
                            ("OFF_DUTY", "Off Duty"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
